name: utf
version: 0.9.0+5

description: Provides common operations for manipulating Unicode sequences
author: Dart Team <misc@dartlang.org>
homepage: https://www.github.com/dart-lang/utf

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
